tools/virtio: add missing device-id/virtio.h wrapper header
Since commit ecca1d63c1ea ("Replace <linux/mod_devicetable.h> by more
specific <linux/device-id/*.h> (headers)"), includes
<linux/device-id/virtio.h> instead of the old <linux/mod_devicetable.h>.
However, tools/virtio/ only had a wrapper for the old mod_devicetable.h,
causing the build to fail with:

    ./../../include/linux/virtio.h:10:10: fatal error: linux/device-id/virtio.h: No such file or directory

Add the missing wrapper header that redirects to
../../include/linux/device-id/virtio.h

Signed-off-by: Longjun Tang <tanglongjun@kylinos.cn>
Message-ID: <20260909092000.107827-1-lange_tang@163.com>
Signed-off-by: Michael S. Tsirkin <mst@redhat.com>